spring:
  profiles:
    active: mysql

---

spring:
  config:
    activate:
      on-profile: mongo

  data:
    mongodb:
      uri: mongodb://localhost:27017/test

---

spring:
  config:
    activate:
      on-profile: postgres

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password:

---

spring:
  config:
    activate:
      on-profile: mysql

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: test

#logging:
#  level:
#    root: info
#  file:
#    path: "~/excelParser/logs"