spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: wonyonghwang


logging:
  level:
    root: info
#  file:
#    path: "~/excelParser/logs"