version: "3.9"

services:
  mysql:
    platform: linux/amd64
    container_name: mysql8.0.34
    image: 'mysql:8.0.34'
    volumes:
      - data:/data/mysql
      - ./env/init.sql:/docker-entrypoint-initdb.d/init.sql # 초기 데이터 삽입 관련
    env_file:
      - ./env/mysql.env
    ports:
      - "33060:3306"

volumes:
  data:
